using Microsoft.AspNetCore.Authentication.Cookies;using Microsoft.AspNetCore.DataProtection;using Microsoft.EntityFrameworkCore;using ServerWatch.Core.Models;using ServerWatch.Core.Monitoring;using ServerWatch.Infrastructure.Data;using ServerWatch.Infrastructure.Monitoring;
var builder=WebApplication.CreateBuilder(args);builder.Logging.ClearProviders();builder.Logging.AddJsonConsole();var keysPath=builder.Configuration["DataProtection:KeysPath"]??"data-protection-keys";builder.Services.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo(keysPath)).SetApplicationName("ServerWatch");
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(o=>{o.LoginPath="/Login";o.AccessDeniedPath="/Login";o.Cookie.Name="ServerWatch.Auth";o.Cookie.HttpOnly=true;o.Cookie.SameSite=SameSiteMode.Strict;o.ExpireTimeSpan=TimeSpan.FromHours(12);});
builder.Services.AddAuthorization();builder.Services.AddRazorPages(o=>{o.Conventions.AuthorizeFolder("/");o.Conventions.AllowAnonymousToPage("/Login");});builder.Services.AddHealthChecks();
builder.Services.AddDbContext<ServerWatchDbContext>(o=>{var provider=builder.Configuration["DatabaseProvider"]??"Sqlite";var cs=builder.Configuration.GetConnectionString("ServerWatch")??"Data Source=serverwatch.db";if(provider.Equals("SqlServer",StringComparison.OrdinalIgnoreCase))o.UseSqlServer(cs);else o.UseSqlite(cs);});
builder.Services.AddHttpClient("monitor",c=>c.DefaultRequestHeaders.UserAgent.ParseAdd("ServerWatch/4.0"));builder.Services.AddHttpClient("alerts",c=>c.DefaultRequestHeaders.UserAgent.ParseAdd("ServerWatch/4.0"));builder.Services.Configure<AlertOptions>(builder.Configuration.GetSection("Alerts"));builder.Services.AddSingleton<MonitorRunQueue>();builder.Services.AddSingleton<IAlertSender,AlertSender>();builder.Services.AddSingleton<IMonitorCheck,PingMonitorCheck>();builder.Services.AddSingleton<IMonitorCheck,TcpMonitorCheck>();builder.Services.AddSingleton<IMonitorCheck,HttpMonitorCheck>();builder.Services.AddSingleton<IMonitorCheck,SqlMonitorCheck>();builder.Services.AddHostedService<MonitoringWorker>();
var app=builder.Build();if(!app.Environment.IsDevelopment()){app.UseExceptionHandler("/Error");app.UseHsts();}app.UseHttpsRedirection();app.UseStaticFiles();app.UseRouting();app.UseAuthentication();app.UseAuthorization();app.MapHealthChecks("/health").AllowAnonymous();app.MapRazorPages();
using(var scope=app.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<ServerWatchDbContext>();await DatabaseUpgrade.ApplyAsync(db);if(!db.MonitorTargets.Any()){db.MonitorTargets.AddRange(new MonitorTarget{Name="PUBLIC-WEB",Host="https://example.com",CheckType="HTTP",IntervalSeconds=60},new MonitorTarget{Name="CLOUDFLARE-DNS",Host="1.1.1.1",CheckType="Ping",IntervalSeconds=60},new MonitorTarget{Name="HTTPS-PORT",Host="example.com",CheckType="TCP",Port=443,IntervalSeconds=60});await db.SaveChangesAsync();}}
app.Run();
